### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by wKich** [skbkontur/react-sorge#1]
- package-lock.json не нужен
- Прибрать опции в tsconfig.json/.prettierrc
- Добавить readme
- `require.resolve()` для лоадеров в webpack.config.js не обязателен
- Конфиги сторибука и вебпака можно описывать на TypeScript'е
- Если перевести сборку на babel, то в конфиге вебпака можно будет задавать только опцию test для babel-loader, например вот так `config.module.rules[0].test = /\.(mjs|(j|t)sx?)$/;`
- Правило и лоадер для шрифтов не нужен, в дефолтном конфиге есть для этого правило
- react должен быть в peerDeps
- Нужно добавить .npmignore, нет смысла паблишить сорцы, сторибук
- Параметр "main" в package.json ведет на несуществующий файл
- Зачем-то установлен tslint-config-prettier, хотя самого tslint'а нет
- Зависимость "storybook" не нужна
- Сторисы какие-то немного странные. Сами сторисы в файле test.tsx, где kind имеет название "Button", хелпер компоненты кажется можно заинлайнить или вынести другие хелпер компоненты из сторисов. В общем надо причесать это дело.
- Listener.on возвращает ссылку на метод off, хотя сам метод публичный. При этом off метод возвращает инстанс на самого Listnera. Будет лучше, если на on вернется функция для отписки вида `() => this.listeners.delete(handler)`. Тогда можно будет выкинуть метод off
- Конструктор в Listener можно переписать в гораздо короткий вид `public constructor(private readonly filter: H | null = null) {}`
- Можно не делать проверку typeof у фильтра
- Вообще судя по коду фильтр никак не используется. Наружу торчит Sorge или SorgeNode, а Sorge это singletone
- `findAmongChildren` если у fiber есть сосед и ребенок, то поиск по детям будет проигнорирован
- Кажется нет смысла делать `attributesToObject` в `translatePropsToAttributes`, чтобы потом сделать Object.entries

**Comment by lossir** [comment]
## Сборка
- [x] package-lock.json не нужен
- [ ] Прибрать опции в tsconfig.json/.prettierrc
- [ ] Добавить readme
- [x] `require.resolve()` для лоадеров в webpack.config.js не обязателен
- Конфиги сторибука и вебпака можно описывать на TypeScript'е
- Если перевести сборку на babel, то в конфиге вебпака можно будет задавать только опцию test для babel-loader, например вот так `config.module.rules[0].test = /\.(mjs|(j|t)sx?)$/;`
- Правило и лоадер для шрифтов не нужен, в дефолтном конфиге есть для этого правило
- [ ] react должен быть в peerDeps
- [ ] 🤔Нужно добавить .npmignore, нет смысла паблишить сорцы, сторибук
- [ ] Параметр "main" в package.json ведет на несуществующий файл
- [ ] Зачем-то установлен tslint-config-prettier, хотя самого tslint'а нет
- [ ] 🤔Зависимость "storybook" не нужна
- [ ] Сторисы какие-то немного странные. Сами сторисы в файле test.tsx, где kind имеет название "Button", хелпер компоненты кажется можно заинлайнить или вынести другие хелпер компоненты из сторисов. В общем надо причесать это дело.
- [ ] Listener.on возвращает ссылку на метод off, хотя сам метод публичный. При этом off метод возвращает инстанс на самого Listnera. Будет лучше, если на on вернется функция для отписки вида `() => this.listeners.delete(handler)`. Тогда можно будет выкинуть метод off
- [ ] Конструктор в Listener можно переписать в гораздо короткий вид `public constructor(private readonly filter: H | null = null) {}`
- [ ] Можно не делать проверку typeof у фильтра
- [ ] Вообще судя по коду фильтр никак не используется. Наружу торчит Sorge или SorgeNode, а Sorge это singletone
- [ ] `findAmongChildren` если у fiber есть сосед и ребенок, то поиск по детям будет проигнорирован
- [ ] Кажется нет смысла делать `attributesToObject` в `translatePropsToAttributes`, чтобы потом сделать Object.entries
